name = "HypertextTemplates"
uuid = "c7d46f9d-34c3-4420-bf57-257f25aec718"
version = "2.2.3"
authors = ["Michael Hatherly <michaelhatherly@gmail.com>"]

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[extensions]
HypertextTemplatesBonitoExt = "Bonito"
HypertextTemplatesCommonMarkExt = "CommonMark"
HypertextTemplatesHTTPExt = "HTTP"
HypertextTemplatesReviseExt = "Revise"

[compat]
CodeTracking = "1.3, 2, 3"
CommonMark = "0.10"
InteractiveUtils = "1.6"
MacroTools = "0.5"
PackageExtensionCompat = "1"
TOML = "1"
julia = "1.6"
